/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package _/D_/GitHub/ExcelDLL2/Golang */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */


#line 4 "main.go"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "common.h"

#line 1 "cgo-generated-wrapper"


/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


extern void NewFile();

extern void OpenFile(char* p0, char* p1);

extern int NewSheet(char* p0);

extern void GetCellValue(char* p0, char* p1, char* p2, char* p3);

extern void SetCellValue(char* p0, char* p1, char* p2, char* p3);

extern void AddPicture(char* p0, char* p1, char* p2, char* p3, char* p4);

extern int GetActiveSheetIndex();

extern void SetActiveSheet(int p0);

extern void GetSheetName(int p0, char* p1);

extern void SetSheetName(char* p0, char* p1);

extern int GetSheetIndex(char* p0);

extern int GetSheetCount();

extern void DeleteSheet(char* p0);

extern void CopySheet(int p0, int p1, char* p2);

extern int GetRowCount(char* p0, char* p1);

extern int GetColumnCount(char* p0, int p1, char* p2);

extern void SetRowHeight(char* p0, int p1, double p2, char* p3);

extern double GetRowHeight(char* p0, int p1, char* p2);

extern void RemoveRow(char* p0, int p1, char* p2);

extern void InsertRow(char* p0, int p1, char* p2);

extern void DuplicateRowTo(char* p0, int p1, int p2, char* p3);

extern void SetCellInt(char* p0, char* p1, int p2, char* p3);

extern void SetCellBool(char* p0, char* p1, int p2, char* p3);

extern void SetCellFloat(char* p0, char* p1, double p2, int p3, int p4, char* p5);

extern void SetCellStr(char* p0, char* p1, char* p2, char* p3);

extern void SetCellDefault(char* p0, char* p1, char* p2, char* p3);

extern void GetCellFormula(char* p0, char* p1, char* p2, char* p3);

extern void Save(char* p0);

extern void SaveAs(char* p0, char* p1);

#ifdef __cplusplus
}
#endif
